### ISSUE TITLE
Building from current git source

### ISSUE THREAD

**Issue by joerenzullo** [squaresLab/BugZoo#123]
Ran into this:
```
error: Could not find suitable distribution for Requirement.parse('Werkzeug>=0.7')
```

fixed it with
```
joe@b120ba:~/BugZoo$ pip3 install -U Werkzeug
```

Then was able to add the source with
```
bugzoo source add https://github.com/squaresLab/ManyBugs.git
```

(it needed the .git)

**Comment by ChrisTimperley** [comment]
That's interesting. Could you let me know what version of Python you're using? Also, I don't suppose you happened to already have a version of Werkzeug installed on the server?

**Comment by joerenzullo** [comment]
3.6.3, and there was no version previously installed. I've been setting it up on my desktop at work (an Ubuntu 17.10 machine) since I'm still waiting on ASU to get docker installed on the clusters.

I did get bugzoo to import the ManyBugs set just before I left this afternoon, so will try to get up and running with proper code tomorrow.

**Comment by ChrisTimperley** [comment]
It looks like BugZoo likely depends on Werkzeug and Flask being a certain version or later. I can try to figure out those versions and add them to `setup.py`.

On my machine, I'm currently using:

```
Flask (0.12.2)
Werkzeug (0.14.1)
```

**Comment by ChrisTimperley** [comment]
Since this issue is resolved, I'm going to go ahead and close the issue. I think the problem may have been due to not calling `pip install` with `--upgrade`. The installation instructions should be updated to reflect this, and, better yet, to give instructions on how to install `bugzoo` to a virtual environment (which should be the preferred method).
