### ISSUE TITLE
Instrument code to handle signals that prevent creation of `.gcda` files for coverage

### ISSUE THREAD

**Issue by afsafzal** [squaresLab/BugZoo#145]
If the code doesn't exit normally, `.gcda` files won't be created. We need to instrument code to handle signals and force it to call `exit()`:
```
// SHURIKEN :: INSTRUMENTATION :: START
#include <stdio.h>
#include <signal.h>
#include <stdlib.h>
void shuriken_sighandler(int sig)
{
  printf("received signal\n");
  exit(1);
}
void shuriken_ctor (void) __attribute__ ((constructor));
void shuriken_ctor (void)
{
  struct sigaction new_action;
  new_action.sa_handler = shuriken_sighandler;
  sigemptyset(&new_action.sa_mask);
  new_action.sa_flags = 0;
  sigaction(SIGTERM, &new_action, NULL);
  sigaction(SIGINT, &new_action, NULL);
  sigaction(SIGKILL, &new_action, NULL);
}
// SHURIKEN :: INSTRUMENTATION :: END
```

**Comment by ChrisTimperley** [comment]
Unfortunately we need to inject this instrumentation into a single source file that is used to build the binary. Trying to inject it into multiple files will throw linker errors due to multiple definitions of `shuriken_ctor`. We either need to find those source files automatically, or else we may need the user to provide a list of source code files that should be instrumented.

**Comment by afsafzal** [comment]
I think we should go with user provided list for now, and find an automatic way to do it later.

**Comment by afsafzal** [comment]
Or can we create unique method names instead of `shuriken_ctor`?
