### ISSUE TITLE
gmp-bug-13420-13421 fails to compile

### ISSUE THREAD

**Issue by ChrisTimperley** [squaresLab/BugZoo#18]
A Makefile input seems to be missing from the ManyBugs archive?

```
[vagrant@localhost gmp]$ ./configure --build=i686-linux-gnu "CFLAGS=-m32" "CXXFLAGS=-m32" "LDFLAGS=-m32"
checking build system type... i686-pc-linux-gnu
checking host system type... i686-pc-linux-gnu
...
config.status: error: cannot find input file: `tests/mpbsd/Makefile.in'
```

There appears to be no `tests/mpbsd` directory, although there is a `mpbsd/Makefile.in` within the `gmp` directory.

Is the result of losing hard symbolic links during the extraction of the ManyBugs archive? No errors were thrown during extraction on Cygwin, but F22 threw plenty. If so, I _might_ be able to extract the symlinks by tricking F22 into believing it has the same directory structure as the original ManyBugs machine (via chroot); even then, files would have to be extracted in the correct order.

**Comment by eduardodx** [comment]
I've stumbled upon this same problem inside the chroot.
I've managed to make this work removing all the references of `*mpbsd/Makefile*` from the `configure` file.
Although this is a hack, I think is plausible for us because we're not running the scenario in a BSD environment.
btw The sanity is working as expected.

**Comment by ChrisTimperley** [comment]
Nice! I'll give that a go on the Docker container.

**Comment by eduardodx** [comment]
Okay!

**Comment by ChrisTimperley** [comment]
Incorporated fix into `many-bugs/gmp/Dockerfile.bug`.
