### ISSUE TITLE
Compilation of php fails with configure: error: C compiler cannot create executables

### ISSUE THREAD

**Issue by manishmotwani3** [squaresLab/BugZoo#53]
For php scenario AutomatedRepairBenchmarks.c/manybugs/php/php-bug-2011-03-11-d890ece3fc-6e74d95f34, running the prepare.sh script terminates with error "configure: error: C compiler cannot create executables". Please find attached the config.log. 
[config.log.txt](https://github.com/ChrisTimperley/RepairBox/files/724743/config.log.txt)

**Comment by ChrisTimperley** [comment]
We're moving from supporting as many platforms as possible to providing a single, canonical "repair box" for each bug, in the form of a Docker container. I'll add some basic instructions to the README this afternoon explaining how to get started with things.

In the mean time, whilst I haven't pushed the Docker images for each bug to DockerHub, you can install them by cloning the repository (using the command given in the README), then executing the following instructions:

```
$ cd location-of-the-repo
$ make -C base
$ make -C manybugs/base
$ make -C manybugs/php
```

Once you've done that, you should have all of the PHP repair boxes loaded onto your machine, each of which provides a minimal environment for replicating that particular bug. You can then access one of these boxes (note that they're ephemeral) using the following command:

```
$ docker run --rm -it christimperley/repairbox:php-bug-2011-03-11-d890ece3fc-6e74d95f34
```

Most likely, you'll want to install some software onto the repair box (in order to perform your analysis), whilst avoiding the need to re-install everytime you access the container. To do that, you can create a new Dockerfile which builds on top of the RepairBox:

```
FROM christimperley/repairbox:php-bug-2011-03-11-d890ece3fc-6e74d95f34

RUN download-my-software
```

You can then go and build your container using the following command:

```
$ cd dir-with-docker-file
$ docker build -t name-of-my-container .
```

**Comment by ChrisTimperley** [comment]
Updated README.md

**Comment by manishmotwani3** [comment]
I am getting error while running make -C manybugs/php for the scenario php-bug-2012-01-29-d8b312845c-dc27324dd9. Following is the error. 


rm -f php-bug-2012-01-29-d8b312845c-dc27324dd9/Dockerfile
cp Dockerfile.bug php-bug-2012-01-30-9de5b6dc7c-4dc8b1ad11/Dockerfile
docker build -t christimperley/repairbox:manybugs-php-2012-01-30-9de5b6dc7c-4dc8b1ad11 php-bug-2012-01-30-9de5b6dc7c-4dc8b1ad11
Sending build context to Docker daemon 23.88 MB
Step 1 : FROM christimperley/repairbox:manybugs-php
 ---> bf05ccd6f414
Step 2 : ADD bug-info /experiment/bug-info
 ---> Using cache
 ---> 7059c9c57020
Step 3 : ADD diffs /experiment/diffs
 ---> Using cache
 ---> bfa3f160e90b
Step 4 : ADD fixed /experiment/fixed
 ---> Using cache
 ---> 303d548e2347
Step 5 : ADD preprocessed /experiment/preprocessed
 ---> Using cache
 ---> 652b96325bd1
Step 6 : ADD src.tar.gz /experiment
 ---> Using cache
 ---> 07350a9249c0
Step 7 : ADD test.sh /experiment
 ---> Using cache
 ---> be5cf1d5bf5b
Step 8 : ADD test.pl /experiment
 ---> Using cache
 ---> 5e5baaaf5435
Step 9 : ADD configuration-default /experiment
 ---> Using cache
 ---> b6554fe94d56
Step 10 : ADD problem.json /experiment
 ---> Using cache
 ---> f346bffeffe4
Step 11 : RUN cd /experiment &&     mv libxml.patch src &&     cd src &&     cat libxml.patch | patch -p0 &&     rm libxml.patch &&     ./configure --disable-phar
 ---> Running in d5193b060774
patching file ext/dom/node.c
patching file ext/dom/documenttype.c
patching file ext/simplexml/simplexml.c
configure: error: cannot find sources (README.GIT-RULES) in . or ..
The command '/bin/sh -c cd /experiment &&     mv libxml.patch src &&     cd src &&     cat libxml.patch | patch -p0 &&     rm libxml.patch &&     ./configure --disable-phar' returned a non-zero code: 1
make: *** [php/2012-01-30-9de5b6dc7c-4dc8b1ad11] Error 1

**Comment by ChrisTimperley** [comment]
So this particular bug scenario has a rather skewed `source` directory, and in particular, a `configure` script that only runs on the ManyBugs VM.

After installing autoconf and running `./buildconf` within the `source` directory, the program configures and compiles correctly. I'll update the PHP Dockerfile accordingly.
